import {Platform, StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    height: 200,
    flexDirection: 'row',
    shadowColor: 'black',
    shadowOffset: {width: 5, height: 5},
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  lineAndIconContainer: {
    height: 200,
    width: 60,
    alignItems: 'center',
    borderRadius: 1,
  },
  line: {
    height: '100%',
    width: 1,
    borderWidth: 2,
    borderColor: '#134074',
    zIndex: 1,
  },
  iconContainer: {
    zIndex: 99,
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    height: 200,
  },
  icon: {
    height: 30,
    width: 30,
    borderRadius: 99,
    backgroundColor: '#134074',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: '#134074',
  },
  entryInfoContainer: {
    flex: 1,
    flexDirection: 'column',
    overflow: 'hidden',
    borderRadius: 5,
    marginBottom: 30,
    marginTop: 10,
    marginRight: 20,
  },
  dateContainer: {
    height: 30,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(19, 64, 116, 0.9)',
  },
  date: {
    fontSize: 16,
    fontFamily: 'Quicksand',
    color: '#FFFF',
    fontWeight: '800',
  },
  feelingContainer: {
    height: 80,
    alignItems: 'center',
    justifyContent: 'center',
  },
  feeling: {
    fontSize: 30,
    fontFamily: 'Quicksand',
    color: '#FFFF',
    fontWeight: '800',
    shadowColor: 'black',
    shadowOffset: {width: 3, height: 3},
    shadowOpacity: 0.4,
    shadowRadius: 3,
    textTransform: 'capitalize',
  },
  noteContainer: {
    height: 50,
    width: '100%',
    justifyContent: 'center',
    backgroundColor: 'rgba(19, 64, 116, 0.7)',
    alignItems: 'flex-start',
    paddingHorizontal: 15,
  },
  note: {
    color: 'black',
    textAlign: 'center',
    fontSize: 16,
    fontFamily: 'Quicksand',
    color: 'rgba(225,225,225,1)',
    fontWeight: '800',
  },
});
